...@name_basics
...@title_akas
...@title_basics
...@title_crew
...@title_episode
...@title_principal
...@title_ratings

title_crew.tconst -> title_basics.tconst
title_episode.tconst -> title_basics.tconst
title_episode.parentTconst -> title_basics.tconst
title_principal.tconst -> title_basics.tconst
title_ratings.tconst -> title_basics.tconst
title_akas.tconst -> title_basics.tconst
title_principal.nconst -> name_basics.nconst
