name_basics: {
  shape: sql_table
  nconst: string {constraint: primary_key}
  primaryName: string
  birthYear: int
  deathYear: int
  primaryProfession: array(string)
  knownForTitles: array(string)
}