title_basics: {
  shape: sql_table
  tconst: string {constraint: primary_key}
  titleType: string
  primaryTitle: string
  originalTitle: string
  isAdult: bool
  startYear: int
  endYear: string
  runtimeMinutes: int
  genres: array(string)
}