title_akas: {
  shape: sql_table
  tconst: string {constraint: foreign_key}
  ordering: int
  title: string
  region: string
  language: string
  types: array(string)
  attributes: array(string)
  isOriginalTitle: bool
}